baseURL = 'https://sehheiden.github.io/'
languageCode = 'en-us'
title = "SeHe's Blog"
theme = "diary"

[params]
  favicon = "/logo.ico"
  enableReadingTime=true
  enableUtterances = true
  customCSS = ["css/custom.css"]

[params.utterances]
  repo="sehHeiden/sehHeiden.github.io"
  term="pathname"
  theme="github-dark"
  crossorigin="anonymous" 

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "About Me"
  url = "/about/"
  weight = 2

  [[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 3
  
  [[menu.main]]
  url = "/categories"
  name = "Categories"
  weight = 4
  
  [[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 5
  
  [[menu.main]]
  url = "/index.xml"
  name = "RSS Feed"
  weight = 6
 
[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
		[markup.goldmark.extensions]
			[markup.goldmark.extensions.passthrough]
			enable = true
			[markup.goldmark.extensions.passthrough.delimiters]
				block = [['$$', '$$']]
				inline = [['$', '$']]
