baseURL = 'https://sehheiden.github.io/'
languageCode = 'en-us'
title = "SeHe's Blog"
theme = "diary"

[params]
  favicon = "/logo.ico"
  enableReadingTime=true

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "About Me"
  url = "/about/"
  weight = 2

  [[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 3
  
  [[menu.main]]
  url = "/categories"
  name = "Categories"
  weight = 4
  
  [[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 5
  
  [[menu.main]]
  url = "/index.xml"
  name = "RSS Feed"
  weight = 6

enableGiscus = true
[params.giscus]
    data-repo="sehHeiden/sehHeiden.github.io"
    data-repo-id="R_kgDOM4jeQg"
    data-category="General"
    data-category-id="DIC_kwDOM4jeQs4Ci57g"
    data-mapping="pathname"
    data-strict="0"
    data-reactions-enabled="1"
    data-emit-metadata="0"
    data-input-position="bottom"
    data-theme="preferred_color_scheme"
    data-lang="en"
    crossorigin="anonymous"
 